# -*- coding: utf-8 -*-
"""task-1_AI & ML INTERNSHIP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3dO-A72S9QDjzqUsgMM1VB32fiRNvVw

Task 1: Data Cleaning & Preprocessing
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

df = pd.read_csv("Titanic-Dataset.csv")
print(df.head())
print(df.info())
print(df.describe())

print(df.isnull().sum())
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df['Cabin'].fillna('Unknown', inplace=True)  # Optional: Drop column if too many nulls

print(df.isnull().sum())

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})  # Label Encoding

df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

print(df.head())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

print(df[['Age', 'Fare']].head())

plt.figure(figsize=(12, 6))
sns.boxplot(x=df['Fare'])
plt.title('Boxplot for Fare')
plt.show()
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['Fare'] >= lower) & (df['Fare'] <= upper)]

sns.boxplot(x=df['Fare'])
plt.title("After Outlier Removal")
plt.show()

print(df.shape)
print(df.head())

